[theme]
primaryColor="#D4AF37"                # EMAAR gold
backgroundColor="#F7F1E1"             # light beige
secondaryBackgroundColor="#F2E8D5"    # card beige
textColor="#2B2B2B"                   # deep charcoal
font="sans serif"
